NUMPY

In [2]:
#NumPy (Numerical Python) is a powerful Python library used for numerical and scientific computing. 
#It provides: Efficient array operations, Mathematical functions, Linear algebra, Random number generation.
#Numpy - universal standard for working with numericals in python.
#contains multidimentional arrays and matrix data structure.
#Numpy array is 50x faster than traditional python lists.
#Array object in numpy is called - ndarray.


In [1]:
#importing numpy
import numpy as np

In [3]:
#creating an array
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
#use a tuple to create a numpy array
y = np.array((5,6,7,8,9))
print(y)
print(type(y))

[5 6 7 8 9]
<class 'numpy.ndarray'>


In [7]:
# Dimension
# In NumPy, dimension (ndim) means: How many axes (directions) are needed to locate an element
# It does NOT directly mean “rows and columns” — that’s just a special case.


In [13]:
#Dimensions in array - 0 dimension
z =np.array(9)
print(z)
print(type(z))
print(z.ndim)
print(z.shape)

9
<class 'numpy.ndarray'>
0
()


In [15]:
#Dimensions in array - 1 dimension
z =np.array((8,7,5,9))
print(z)
print(type(z))
print(z.ndim)
print(z.shape)

[8 7 5 9]
<class 'numpy.ndarray'>
1
(4,)


In [17]:
#Dimensions in array - 2 dimension
z =np.array([[6,8,9],[9,0,7]])
print(z)
print(type(z))
print(z.ndim)
print(z.shape)

[[6 8 9]
 [9 0 7]]
<class 'numpy.ndarray'>
2
(2, 3)


In [23]:
 #Dimensions in array - 3 dimension
z = np.array([[[9,8,7],[6,7,0]],[[9,0,5],[6,6,9]]])
print(z)
print(type(z))
print(z.ndim)
print(z.shape)


[[[9 8 7]
  [6 7 0]]

 [[9 0 5]
  [6 6 9]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)


In [19]:
#create a 5 dimension array - use "ndmin"
a =np.array([5,6,7,8], ndmin=5)
print(a)
print('number of dimentions is',a.ndim)

[[[[[5 6 7 8]]]]]
number of dimentions is 5


In [23]:
# ACCESS ARRAYS
#Numpy array indexing
x = np.array([5,6,7,8])
print(x[1])
print(x[0])
print(x[-1])

6
5
8


In [25]:
#Numpy array indexing in 2D array
y =np.array([[8,9,0],[5,6,7]])
print(y[0,1]) #here [x,y], x denotes which sq bracket and y denotes the element in x denoted bracket.



9


In [31]:
print(y[0,2])
print(y[1,1])

0
6


In [5]:
#add first element of row 1 and last of row 2
y =np.array([[8,9,0],[5,6,7]])
print('first element in row 1 is',y[0,0])
print('last element in row 2 is',y[1,2])
print('sum of elements is', y[0,0]+y[1,2])

first element in row 1 is 8
last element in row 2 is 7
sum of elements is 15


In [43]:
#ACCESS 3D ARRAY
#Access the 3rd element of the 2nd array of the 1st array.
# Syntax: arr[block_index, row_index, column_index]

z =np.array([[[6,7,8],[8,9,0]],[[7,6,5],[9,9,9]]])
print(z[0,1,2])

0


In [39]:
#slicing of numpy array
#1D array
# array[start : stop : step]
                            # start → index to begin (inclusive)
                            # stop → index to end (exclusive)
                            # step → jump size (optional)
a =np.array([5,6,7,8,9])
print(a[1:3])

# arr = np.array([10, 20, 30, 40, 50])

# Expression	     Output	                Explanation
# arr[1]	         20	                    Get element at index 1
# arr[1:4]	         [20 30 40]	            Get elements from index 1 to 3
# arr[:3]	         [10 20 30]	            From start to index 2
# arr[3:]	         [40 50]	            From index 3 to end
# arr[-1]	         50	                    Last element
# arr[::-1]	         [50 40 30 20 10]	    Reverse the array


#2D array
# array[row_start:row_stop, col_start:col_stop]

x= np.array([[8,9,0],[5,6,7]])
print(x[0,1:3])

b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
b[:, 1]     # all rows, column 1 → [2 5 8]
b[1, :]     # row 1 → [4 5 6]
b[:, :]     # entire array


# Extract a submatrix	      arr[1:3, 0:2]
# Get a specific row	      arr[2, :]
# Get a specific column	      arr[:, 1]
# Skip rows or columns	      arr[::2, ::2]
# Reverse rows or columns	  arr[::-1] or arr[:, ::-1]
# Extract diagonals	          np.diag(arr)


#3D array
# array[block_slice, row_slice, column_slice]

z =np.array([[[6,7,5,8,8],[8,9,9,6,0]],[[7,7,9,6,5],[9,9,0,0,9]]])
print(z[0,1,1:4])

c = np.array([
    [[1,  2,  3],
     [4,  5,  6]],

    [[7,  8,  9],
     [10, 11, 12]]
])

c[0]                 # full first block
c[1, :, 1]           # column 1 of block 1 → [8 11]
c[:, 0, :]           # first row of all blocks
c[0:2, 1, 0:2]       # slicing across all dimensions

 

[6 7]
[9 0]
[[1 3]
 [7 9]]


[9 9 6]


array([[ 4,  5],
       [10, 11]])

 #Data types in Numpy

i - integer,
b - boolean,
u - unsigned integer,
f - float,
c - complex float,
m - timedelta,
M - datetime,
O - object,
S - string,
U - unicode string,
V - fixed chunk of memory for other type (void)

In [63]:
#checking the data type of an array
x = np.array([5,6,7,8,9,0])
print(x.dtype)

y = np.array(['xyz','animal','dad','lmop'])
print(y.dtype)

int32
<U6


In [69]:
#creating array with a defined data type
x = np.array([5,6,7,8,9,0], dtype = 'S')
print(x)
print(x.dtype)

[b'5' b'6' b'7' b'8' b'9' b'0']
|S1


In [71]:
#creating array with data type 4 bytes integer
x = np.array([5,6,7,8,9,0], dtype = 'i4')
print(x)
print(x.dtype)


[5 6 7 8 9 0]
int32


In [73]:
#Numpy array shape
#shape of an array is the number of elements in each dimensions.
x = np.array([[5,6,7,8],[9,8,7,6]])
print(x.shape)

y = np.array([[[5,6,7,8],[7,6,5,8]],[[0,9,8,7],[8,9,7,5]]])
print(y.shape)

(2, 4)
(2, 2, 4)


In [81]:
#joining 1D numpy arrays
x = np.array([5,6,7,8])
y = np.array([0,9,8,6])
print(np.concatenate((x,y)))

[5 6 7 8 0 9 8 6]


In [7]:
#joining 2D numpy arrays
x = np.array([[5,6,7,8],[6,8,9,0]])
y = np.array([[0,9,8,6],[7,6,8,0]])
print(np.concatenate((x,y), axis=1)) #column wise

x = np.array([[5,6,7,8],[6,8,9,0]])
y = np.array([[0,9,8,6],[7,6,8,0]])
print(np.concatenate((x,y), axis=0)) #row wise

[[5 6 7 8 0 9 8 6]
 [6 8 9 0 7 6 8 0]]
[[5 6 7 8]
 [6 8 9 0]
 [0 9 8 6]
 [7 6 8 0]]


In [93]:
#spliting numpy arrays
#splitting array in 3 parts
x = np.array([5,0,9,7,6,5,6,7,8])
print(np.array_split(x,3))


[array([5, 0, 9]), array([7, 6, 5]), array([6, 7, 8])]


In [97]:
x = np.array([5,0,9,7,6,5,6,7,8])
print(np.array_split(x,6))

[array([5, 0]), array([9, 7]), array([6, 5]), array([6]), array([7]), array([8])]


In [107]:
#ravel and flatten function - converts multidimentional array to 1D array.
#both ravel and flatten are of same use.
y = np.array([[[5,6,7,8],[7,6,5,8]],[[0,9,8,7],[8,9,7,5]]])
print(y)
print('dimension is', y.ndim)

z = y.ravel()  #ravel function 
print(z)
print('dimension is', z.ndim)


[[[5 6 7 8]
  [7 6 5 8]]

 [[0 9 8 7]
  [8 9 7 5]]]
dimension is 3
[5 6 7 8 7 6 5 8 0 9 8 7 8 9 7 5]
dimension is 1


In [109]:
y = np.array([[[5,6,7,8],[7,6,5,8]],[[0,9,8,7],[8,9,7,5]]])
print(y)
print('dimension is', y.ndim)

z = y.flatten()   #flatten function 
print(z)
print('dimension is', z.ndim)

[[[5 6 7 8]
  [7 6 5 8]]

 [[0 9 8 7]
  [8 9 7 5]]]
dimension is 3
[5 6 7 8 7 6 5 8 0 9 8 7 8 9 7 5]
dimension is 1


In [9]:
# .reshape() method is used to change the shape of a NumPy array.

# array.reshape(rows, columns)

# eg:
x = np.linspace(1, 6, 10)
print(x)



[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]


In [11]:
# array.reshape(rows, columns)


y = x.reshape(-1, 1)
print(y)

# if you don’t want to calculate the number of rows manually, you can pass -1. 
# NumPy will infer the correct number of rows based on the total number of elements.


[[1.        ]
 [1.55555556]
 [2.11111111]
 [2.66666667]
 [3.22222222]
 [3.77777778]
 [4.33333333]
 [4.88888889]
 [5.44444444]
 [6.        ]]


In [111]:
#unique function
k = np.array([5,6,7,9,0,77,66,88,9,6,88,90,70,90])
print(k)
print(np.unique(k))

[ 5  6  7  9  0 77 66 88  9  6 88 90 70 90]
[ 0  5  6  7  9 66 70 77 88 90]


In [113]:
#for getting index position of unique items
k = np.array([5,6,7,9,0,77,66,88,9,6,88,90,70,90])
print(k)
print(np.unique(k, return_index = True))

[ 5  6  7  9  0 77 66 88  9  6 88 90 70 90]
(array([ 0,  5,  6,  7,  9, 66, 70, 77, 88, 90]), array([ 4,  0,  1,  2,  3,  6, 12,  5,  7, 11], dtype=int64))


In [117]:
#for getting how many times an item is repeated
k = np.array([5,6,7,9,0,77,66,88,9,6,88,90,70,90])
print(k)
print(np.unique(k, return_counts = True))


[ 5  6  7  9  0 77 66 88  9  6 88 90 70 90]
(array([ 0,  5,  6,  7,  9, 66, 70, 77, 88, 90]), array([1, 1, 2, 1, 2, 1, 1, 1, 2, 2], dtype=int64))


In [119]:
#Delete
k = np.array([5,6,7,9,0,77,66,88,9,6,88,90,70,90])
print(np.delete(k,[2])) #item at index position 2 is deleted

[ 5  6  9  0 77 66 88  9  6 88 90 70 90]


In [125]:
y = np.array([[5,6,7,8],[7,6,5,8],[0,9,8,7],[8,9,7,5]])
print(y)


[[5 6 7 8]
 [7 6 5 8]
 [0 9 8 7]
 [8 9 7 5]]


In [127]:
print(np.delete(y,1, axis =0))

[[5 6 7 8]
 [0 9 8 7]
 [8 9 7 5]]


In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])


# Array Properties

print(a.shape)       # (2, 3) → 2 rows, 3 columns
print(a.ndim)        # 2 → 2D array
print(a.size)        # 6 → total elements
print(a.dtype)       # int64 (depends on platform)



(2, 3)
2
6
int32


In [11]:
# Array Initialization Methods

print(np.zeros((2, 3)))           # All zeros
print(np.ones((2, 3)))            # All ones
print(np.eye(3))                  # Identity matrix
print(np.full((2, 2), 7))         # Fill with 7



print(np.arange(0, 10, 2))        # [0, 2, 4, 6, 8]

# np.arange(start, stop, step)
#     start = 0: The sequence starts from 0.
#     stop = 10: The sequence stops before 10.
#     step = 2: Each number increases by 2.
# It’s like Python’s built-in range(), but returns a NumPy array.


print(np.linspace(0, 1, 5))       # [0. , 0.25, 0.5 , 0.75, 1. ]

# np.linspace(start, stop, num)
#     start = 0: Start of the range.
#     stop = 1: End of the range.
#     num = 5: Number of values evenly spaced between 0 and 1.
# It creates 5 equally spaced values from 0 to 1 (inclusive).



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [3]:
# NumPy’s random module
import numpy as np
# numpy.random is a submodule in NumPy that provides functions to generate:
    # Random numbers (integers, floats)
    # Random samples from arrays
    # Random numbers from statistical distributions (normal, binomial, Poisson, etc.)

# Random Integers
# np.random.randint(low, high=None, size=None)
    # Returns random integers from low (inclusive) to high (exclusive)
    # If high is None, generates between 0 and low

print(np.random.randint(1, 10))                   # Random int from 1 to 9
print(np.random.randint(5, size=3))               # Array of 3 ints from 0 to 4
print(np.random.randint(10, 20, size=(2, 3)))     # 2x3 array of ints from 10 to 19


8
[4 4 0]
[[18 17 14]
 [13 15 18]]


In [5]:
# Random Floats

# np.random.rand(d0, d1, ..., dn)
    # Generates random floats in range [0, 1) with uniform distribution

# 📌 Examples:


np.random.rand()         # Single float
np.random.rand(3)        # 1D array with 3 floats
np.random.rand(2, 2)     # 2x2 matrix

array([[0.57508515, 0.86658244],
       [0.8390258 , 0.818378  ]])

In [9]:
# Random Samples from Normal Distribution

# np.random.normal(loc=0.0, scale=1.0, size=None)
        # loc: Mean (μ)
        # scale: Standard deviation (σ)
        # size: Output shape

# Example:

np.random.normal(30, 5, size=10)  # 10 values with mean=30, std=5

array([36.11294765, 29.3223152 , 26.39004959, 31.05663778, 27.75634505,
       29.82500336, 28.83727916, 32.06201111, 26.70468423, 23.84498044])

In [11]:
 # Random Choice from a List

# np.random.choice(a, size=None, replace=True, p=None)
    # Randomly selects elements from array a
    # replace: Can elements be selected more than once?
    # p: Probabilities for each element

# Example:


np.random.choice([10, 20, 30], size=5)

array([30, 10, 10, 10, 20])

In [ ]:
# Set Seed for Reproducibility

np.random.seed(42)
# Ensures same output every time you run the script.

# It sets the starting point (or "seed") for the random number generator. 
# Once set, all random numbers after it will be predictable and repeatable.

In [15]:
# Mathematical Operations
# These operations apply element-wise:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     # [5 7 9]
print(a * 2)     # [2 4 6]
print(a ** 2)    # [1 4 9]
print(np.sqrt(a))  # [1. 1.41 1.73]

[5 7 9]
[2 4 6]
[1 4 9]
[1.         1.41421356 1.73205081]


Broadcasting: Broadcasting allows NumPy to perform operations between arrays of different shapes without explicitly copying data.


In [ ]:
# Broadcasting is NumPy’s way of performing operations on arrays of different shapes 
# without explicitly copying data, by virtually expanding smaller arrays.

# Add scalar to array
a = np.array([1, 2, 3])
print(a + 5)                    # [6 7 8]    


Add 1D array to 2D array
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])

print(A + B)        
# Output:
# [[11 22 33]
#  [14 25 36]]
# Here, the 1D array B is broadcast across the rows of matrix A.


# Broadcasting Rules: To be broadcast-compatible, two arrays must follow these rules:
# When NumPy operates on two arrays:
    # Compare shapes from the rightmost dimension
    # For each dimension:
        # Sizes must be equal, or
        # One of them must be 1
        # If neither condition holds → error

# A Shape 	   B Shape	          Result
# (3, 3)	   (3,)	             ✅ Broadcast across rows
# (3, 1)	   (3, 3)	         ✅ compatible
# (4, 1)	   (1, 5)	         ✅ Becomes (4, 5)
# (3,2)        (3,3)             ❌ Not compatible

In [7]:
# axis=0 → Acts down the rows → column-wise operation

# axis=1 → Acts across the columns → row-wise operation

# Axis number tells you the direction that COLLAPSES (disappears) not the direction that remains.
# axis = 0
# Meaning: 
    # Collapse axis 0 (rows)
    # Operation moves downwards
    # Result keeps columns
# axis = 1
# Meaning:
    # Collapse axis 1 (columns)
    # Operation moves horizontally
    # Result keeps rows

# axis=0 → rows
# axis=1 → columns
# That is wrong thinking.
# Correct thinking: axis = dimension that gets REMOVED


import numpy as np
X = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


# Sum column-wise (axis=0):

np.sum(X, axis=0)     # [12, 15, 18]   sum of each column


# Sum row-wise (axis=1):

np.sum(X, axis=1)   # [6, 15, 24]   sum of each row



array([ 6, 15, 24])

In [3]:
# np.argmax is a NumPy function used to find the index of the maximum value in an array.

# Basic Syntax: np.argmax(array, axis=None)

    # array: Input array
    # axis (optional): Axis along which to find the max index
    # axis=None (default): treats array as flat (1D)
    # axis=0: finds index of max along each column
    # axis=1: finds index of max along each row

arr = np.array([10, 5, 23, 7])
index = np.argmax(arr)
print(index)                  #  2, index of max value (23)


2


In [ ]:
# np.argmax for 2D Array (Matrix)

Array = np.array([[1, 3, 5],
                  [7, 2, 4]])

np.argmax(Array)           # Output: 3

# Explanation: Flattens the array to [1, 3, 5, 7, 2, 4] and 7 is at index 3.



# Max index column-wise:

np.argmax(Array, axis=0)        # Output: [1 0 0]

# Explanation:
    # Column 0: max = 7 → index = 1
    # Column 1: max = 3 → index = 0
    # Column 2: max = 5 → index = 0

# Max index row-wise:

np.argmax(Array, axis=1)        # Output: [2 0]

# Explanation:
    # Row 0: max = 5 → index = 2
    # Row 1: max = 7 → index = 0

In [17]:
# Masking
# Masking is when you use a boolean condition to index or manipulate elements in an array.

# A mask is just a boolean array (True / False) of the same shape as your data array.
# Wherever the mask is True, NumPy performs the operation (like select, assign, or modify).


arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25   # Boolean mask: [False, False, True, True, True]

# Now you can use this mask to extract values:


print(arr[mask])          #  ➝ array([30, 40, 50])

# or simply
print(arr[arr > 25])            #  ➝ array([30, 40, 50])


[30 40 50]
[30 40 50]


In [19]:
# Modify values using the mask:

arr[arr > 25] = 99
print(arr)            #➝ [10, 20, 99, 99, 99]

[10 20 99 99 99]


In [39]:
# Masking in 2D Arrays

matrix = np.array([
    [10, 15, 20],
    [25, 30, 35],
    [40, 45, 50]
])

mask = matrix > 30
print(mask)

# Output:
        # [[False False False]
        #  [False False  True]
        #  [ True  True  True]]

print(matrix[mask])         #➝ array([35, 40, 45, 50])

count = np.sum(mask)        #➝ Gives count of matrix > 30
print(count)                

# Since True = 1 and False = 0, summing this array gives the count of days where the condition was True.
# # np.sum([[False False False]
 #         [False False  True]
 #         [ True  True  True]])        ➝ 4

[[False False False]
 [False False  True]
 [ True  True  True]]
[35 40 45 50]
4


In [29]:
# Replace all values < 30 with 0
matrix[matrix < 30] = 0

matrix

array([[ 0,  0,  0],
       [ 0, 30, 35],
       [40, 45, 50]])

In [33]:
# Example

temps = np.array([28, 31, 34, 25, 30])
hot_days = temps > 30
print("Hot days:", temps[hot_days])        #➝ [31, 34]

Hot days: [31 34]


In [ ]:
# Combine Masks

# Marks between 50 and 80
# mask = (marks >= 50) & (marks <= 80)
# print(marks[mask])


# Use &, |, ~ for AND, OR, NOT.
# Wrap each condition in parentheses!